/*
 * SSDT-IGPU.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-02
 * Motherboard: Gigabyte Z390 AORUS PRO
 * Chipset: Intel Z790
 * Device Type: GPU
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "IGPU", 0x00000000)
{
    // External references
    External (_SB_.PCI0, DeviceObj)
    External (_SB_.PCI0.LPCB, DeviceObj)
    External (_SB_.PCI0.PEG0, DeviceObj)
    External (_SB_.PCI0.SAT0, DeviceObj)
    External (_SB_.PCI0.XHCI, DeviceObj)
    
    Scope (\)
    {
        // DTGP method - required for _DSM methods
        Method (DTGP, 5, NotSerialized)
        {
            If (LEqual (Arg0, Buffer (0x10)
                {
                    /* 0000 */  0xC6, 0xB7, 0xB5, 0xA0, 0x18, 0x13, 0x1C, 0x44,
                    /* 0008 */  0xB0, 0xC9, 0xFE, 0x69, 0x5E, 0xAF, 0x94, 0x9B
                }))
            {
                If (LEqual (Arg1, One))
                {
                    If (LEqual (Arg2, 0x03))
                    {
                        If (LEqual (Arg3, Buffer (0x04)
                            {
                                0x00, 0x00, 0x00, 0x03
                            }))
                        {
                            If (LEqual (Arg4, Zero))
                            {
                                Return (Buffer (One) { 0x03 })
                            }
                        }
                    }
                }
            }
            
            Return (Buffer (One) { 0x00 })
        }
    }
    
    // SSDT-IGPU implementation
    Scope (_SB.PCI0)
    {
        Device (IGPU)
        {
            Name (_HID, "APP0001")
            Name (_CID, "PNP0C02")
            
            Method (_STA, 0, NotSerialized)
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (0x00)
                }
            }
            
            Method (_DSM, 4, Serialized)
            {
                Store (Package (0x04)
                {
                    "AAPL,slot-name",
                    Buffer () { "Generated Slot" },
                    "model",
                    Buffer () { "SSDT-IGPU Device" },
                    "built-in",
                    Buffer (One) { 0x01 }
                }, Local0)
                
                DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                Return (Local0)
            }
        }
    }
}