/*
 * SSDT-TMR.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "TMR", 0x00000000)
{
External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)
    
    Scope (\_SB.PC00.LPCB)
    {
        Device (TMR)
        {
            Name (_HID, "PNP0100")  // System Timer
            Name (_CID, "PNP0100")
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)
            }
            
            // Standard 8254 timer resources
            Name (_CRS, ResourceTemplate ()
            {
                IO (Decode16, 0x0040, 0x0040, 0x01, 0x01)
                IO (Decode16, 0x0041, 0x0041, 0x01, 0x01)
                IO (Decode16, 0x0042, 0x0042, 0x01, 0x01)
                IO (Decode16, 0x0043, 0x0043, 0x01, 0x01)
                IRQ (Edge, ActiveHigh, Exclusive, ) {0}
            })
        }
    }
}