/*
 * SSDT-PWRB.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "PWRB", 0x00000000)
{

    External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)
    External (_SB_.PC00.LPCB.EC, DeviceObj)  // Embedded Controller
External (\_SB.PWRB, MethodObj)    // 5 Arguments
    
    // Power Button Device under Embedded Controller (recommended for Intel systems)
    Scope (\_SB.PC00.LPCB.EC)
    {
        Device (PWRB)
        {
            Name (_HID, EisaId ("PNP0C0C"))  // Power Button Device
            Name (_CID, "PNP0C0C")
            Name (_UID, 0x01)
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)  // Always present and enabled
            }
            
            // Power Button Status
            Name (_PRS, Package (0x02)
            {
                0x00,   // Not pressed
                0x01    // Pressed
            })
            
            // Power Button Control Method
            Method (_PRW, 0, NotSerialized)
            {
                // Power Resources for Wake
                Return (Package (0x02)
                {
                    0x1B,  // GPE number for power button (typical: GPE 0x1B or 0x1C)
                    0x03   // Sleep state support (S3 and S4)
                })
            }
            
            // Power Button Press Method
            Method (_PSW, 1, NotSerialized)
            {
                // Enable/disable wake capability
                // Arg0: 0=Disable, 1=Enable
                Store (Arg0, PWEN)
            }
            
            // Power Button Notify Method
            Method (_PSB, 0, NotSerialized)
            {
                // Simulate power button press
                Notify (\_SB.PWRB, 0x80)  // Notify power button event
            }
            
            Name (PWEN, 0x01)  // Power button wake enable
        }
    }
}