/*
 * SSDT-MEM2.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "MEM2", 0x00000000)
{
    // Simple memory configuration for macOS
    Scope (\_SB)
    {
        Device (MEM0)
        {
            Name (_HID, "PNP0C80")  // Memory Device
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)
            }
            
            // Memory resources
            Name (_CRS, ResourceTemplate ()
            {
                // System memory
                QWordMemory (ResourceConsumer, PosDecode, MinFixed, MaxFixed, Cacheable, ReadWrite,
                    0x0000000000000000,
                    0x0000000000000000,
                    0xFFFFFFFFFFFFFFFF,
                    0x0000000000000000,
                    0x0000000800000000,  // 32GB
                    ,, , AddressRangeMemory, TypeStatic)
            })
        }
    }
}