/*
 * SSDT-LPCB.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "LPCB", 0x00000000)
{
    // External references (if needed)
    External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)

    Scope (_SB.PC00.LPCB)
    {
        Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
        {
            If (!Arg2)
            {
                Return (Buffer (One)
                {
                     0x03                                             // .
                })
            }

            Return (Package (0x0A)
            {
                "device-id", 
                Buffer (0x04)
                {
                     0x04, 0x7A, 0x00, 0x00                           // .z..
                }, 

                "AAPL,slot-name", 
                Buffer (0x08)
                {
                    "LPC Bus"
                }, 

                "model-name", 
                Buffer (0x15)
                {
                    "Intel LPC Controller"
                }, 

                "name", 
                Buffer (0x10)
                {
                    "pci8086,7a04"
                }, 

                "compatible", 
                Buffer (0x0D)
                {
                    "pci8086,7a04"
                }
            })
        }
    }
}

