/*
 * SSDT-SATA.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "SATA", 0x00000000)
{
    // External references (if needed)
    External (_SB_.PC00, DeviceObj)
  
    External (_SB_.PC00.SAT0, DeviceObj)
External (DTGP, MethodObj)    // 5 Arguments
    
     Method (_SB.PC00.SAT0._DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
    {
        Local0 = Package (0x0C)
            {
                "AAPL,slot-name", 
                Buffer (0x09)
                {
                    "Built In"
                }, 

                "built-in", 
                Buffer (One)
                {
                     0x00                                             // .
                }, 

                "name", 
                Buffer (0x16)
                {
                    "Intel AHCI Controller"
                }, 

                "model", 
                Buffer (0x1F)
                {
                    "Intel Z790 Series Chipset SATA"
                }, 

                "device_type", 
                Buffer (0x15)
                {
                    "AHCI SATA Controller"
                }, 

                "compatible", 
                Buffer (0x0D)
                {
                    "pci8086,a182"
                }
            }
        DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
        Return (Local0)
    }
}

