/*
 * SSDT-NVME.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "NVME", 0x00000000)
{
    Scope (\_SB.PC00.RP01)
    {
        // First NVMe SSD (M.2 Slot 1)
        Device (NVME)
        {
            Name (_ADR, Zero)
            
            Method (_STA, 0, NotSerialized)
            {
                // Check if device is present (you can implement detection logic here)
                Return (0x0F)
            }
            
            // PCI Express Device
            Name (_SUN, 0x01)  // Slot User Number
            
            // Power Management
            Name (_PRW, Package (0x02)
            {
                0x09,  // GPE number
                0x03   // Sleep state support (S3)
            })
            
            // PCI Configuration
            Method (_INI, 0, NotSerialized)
            {
                // Initialization method
                Store (0x01, PCEJ)  // Enable PCI Express slot
            }
            
            // NVMe-specific properties via _DSM
            Method (_DSM, 4, Serialized)
            {
                Local0 = Package (0x02)
                {
                    // NVMe Properties UUID
                    ToUUID ("C5DCDA2A-53C2-481F-BAB5-9F6C79D7C2F5"),
                    
                    Package (0x04)
                    {
                        // "model" - Drive model name
                        "model",
                        Buffer (0x20)
                        {
                            "Samsung SSD 970 EVO Plus 1TB"
                        },
                        
                        // "serial-number" - Drive serial number
                        "serial-number",
                        Buffer (0x14)
                        {
                            "S4EWNF0MC12345"
                        },
                        
                        // "device-type" - NVMe device type
                        "device-type",
                        Buffer (0x04)
                        {
                            0x01, 0x00, 0x00, 0x00  // Non-volatile memory
                        },
                        
                        // "built-in" - Mark as internal device
                        "built-in",
                        Buffer (0x04)
                        {
                            0x01, 0x00, 0x00, 0x00
                        }
                    }
                }
                Return (Local0)
            }
        }
        
        // Second NVMe SSD on same port (if bifurcated)
        Device (NVMF)
        {
            Name (_ADR, 0x00010000)
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)
            }
            
            Name (_SUN, 0x02)
        }
    }
    
    // Second M.2 Slot (RP02)
    Scope (\_SB.PC00.RP02)
    {
        Device (NVME)
        {
            Name (_ADR, Zero)
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)
            }
            
            Name (_SUN, 0x03)
            
            // Different NVMe properties for second slot
            Method (_DSM, 4, Serialized)
            {
                Local0 = Package (0x02)
                {
                    ToUUID ("C5DCDA2A-53C2-481F-BAB5-9F6C79D7C2F5"),
                    
                    Package (0x03)
                    {
                        "model",
                        Buffer (0x20)
                        {
                            "WD Black SN850 2TB"
                        },
                        
                        "serial-number",
                        Buffer (0x14)
                        {
                            "223121801234"
                        },
                        
                        "built-in",
                        Buffer (0x04) { 0x01, 0x00, 0x00, 0x00 }
                    }
                }
                Return (Local0)
            }
        }
    }
}