/*
 * SSDT-PCI0.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "PCI0", 0x00000000)
{
 External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.SAT0, DeviceObj)
    External (_SB_.PC00.XHCI, DeviceObj)
    External (DTGP, MethodObj)    // 5 Arguments

    Method (_SB.PC00.XHCI._DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
    {
        Local0 = Package (0x1B)
            {
                "AAPL,slot-name", 
                Buffer (0x09)
                {
                    "Built In"
                }, 

                "built-in", 
                Buffer (One)
                {
                     0x00                                             // .
                }, 

                "device-id", 
                Buffer (0x04)
                {
                     0x7A, 0x60, 0x00, 0x00                           // z`..
                }, 

                "name", 
                Buffer (0x34)
                {
                    "ASMedia / Intel Z790 Series Chipset XHCI Controller"
                }, 

                "model", 
                Buffer (0x34)
                {
                    "ASMedia ASM1074 / Intel Z790 Series Chipset USB 3.2"
                }, 

                "AAPL,current-available", 
                0x0834, 
                "AAPL,current-extra", 
                0x0A8C, 
                "AAPL,current-in-sleep", 
                0x0A8C, 
                "AAPL,max-port-current-in-sleep", 
                0x0834, 
                "AAPL,device-internal", 
                Zero, 
                "AAPL,clock-id", 
                Buffer (One)
                {
                     0x01                                             // .
                }, 

                "AAPL,root-hub-depth", 
                0x1A, 
                "AAPL,XHC-clock-id", 
                One, 
                Buffer (One)
                {
                     0x00                                             // .
                }
            }
        DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
        Return (Local0)
    }

    Method (_SB.PC00.SAT0._DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
    {
        Local0 = Package (0x0C)
            {
                "AAPL,slot-name", 
                Buffer (0x09)
                {
                    "Built In"
                }, 

                "built-in", 
                Buffer (One)
                {
                     0x00                                             // .
                }, 

                "name", 
                Buffer (0x16)
                {
                    "Intel AHCI Controller"
                }, 

                "model", 
                Buffer (0x1F)
                {
                    "Intel Z790 Series Chipset SATA"
                }, 

                "device_type", 
                Buffer (0x15)
                {
                    "AHCI SATA Controller"
                }, 

                "compatible", 
                Buffer (0x0D)
                {
                    "pci8086,a182"
                }
            }
        DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
        Return (Local0)
    }
}

