/*
 * SSDT-RTC0.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "RTC0", 0x00000000)
{
    // External references (if needed)
 External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)
    Scope (\_SB.PC00.LPCB)
    {
        Device (RTC0)
        {
            Name (_HID, "PNP0B00")
            Name (_CID, "PNP0B00")
            
            Method (_STA, 0, NotSerialized)
            {
                Return (0x0F)
            }
            
            // Standard RTC I/O ports
            Name (_CRS, ResourceTemplate ()
            {
                IO (Decode16, 0x0070, 0x0070, 0x01, 0x02)
                IO (Decode16, 0x0071, 0x0071, 0x01, 0x02)
                IRQ (Edge, ActiveHigh, Exclusive, ) {8}
            })
        }
    }
}