/*
 * SSDT-AWAC.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "AWAC", 0x00000000)
{
    // External references (if needed)
   External (_SB_.PC00, DeviceObj)

    Scope (\_SB.PC00)
    {
        Device (RTC)
        {
            Name (_HID, "PNP0B00" /* AT Real-Time Clock */)  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x02,               // Length
                    )
                IO (Decode16,
                    0x0072,             // Range Minimum
                    0x0072,             // Range Maximum
                    0x01,               // Alignment
                    0x06,               // Length
                    )
            })
            Name (_STA, 0x0B)  // _STA: Status
        }

        Device (AWAC)
        {
            Name (_HID, "ACPI000E" /* Time and Alarm Device */)  // _HID: Hardware ID
            Name (_STA, Zero)  // _STA: Status
        }
    }
}

