/*
 * SSDT-EC.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "EC", 0x00000000)
{
     External (_SB_.PC00.LPCB, DeviceObj)
    External (_SB_.PC00.LPCB.H_EC, DeviceObj)

    Device (EC)
    {
        Name (_HID, EisaId ("PNP0C09") /* Embedded Controller Device */)  // _HID: Hardware ID
        Name (_UID, One)  // _UID: Unique ID
        Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
        {
            IO (Decode16,
                0x0062,             // Range Minimum
                0x0062,             // Range Maximum
                0x01,               // Alignment
                0x01,               // Length
                )
            IO (Decode16,
                0x0066,             // Range Minimum
                0x0066,             // Range Maximum
                0x01,               // Alignment
                0x01,               // Length
                )
        })
        Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            Return (0x0F)
        }

        Method (_REG, 2, NotSerialized)  // _REG: Region Availability
        {
        }
    }
}

