/*
 * SSDT-SBUS.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "SBUS", 0x00000000)
{
    // External references (if needed)
    External (_SB_.PCI0, DeviceObj)
    External (_SB_.PCI0.LPCB, DeviceObj)
    External (_SB_.PCI0.PEG0, DeviceObj)
    External (_SB_.PCI0.SAT0, DeviceObj)
    
    Scope (\)
    {
        // DTGP method - required for _DSM methods
        Method (DTGP, 5, NotSerialized)
        {
            If (LEqual (Arg0, Buffer (0x10)
                {
                    /* 0000 */  0xC6, 0xB7, 0xB5, 0xA0, 0x18, 0x13, 0x1C, 0x44,
                    /* 0008 */  0xB0, 0xC9, 0xFE, 0x69, 0x5E, 0xAF, 0x94, 0x9B
                }))
            {
                If (LEqual (Arg1, One))
                {
                    If (LEqual (Arg2, 0x03))
                    {
                        If (LEqual (Arg3, Buffer (0x04)
                            {
                                0x00, 0x00, 0x00, 0x03
                            }))
                        {
                            If (LEqual (Arg4, Zero))
                            {
                                Return (Buffer (One) { 0x03 })
                            }
                        }
                    }
                }
            }
            
            Return (Buffer (One) { 0x00 })
        }
    }
}