/*
 * SSDT-FWHD.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "FWHD", 0x00000000)
{
    External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)

    Scope (\_SB.PC00.LPCB)
    {
        Device (FWHD)
        {
            Name (_HID, EisaId ("INT0800"))  // Intel Firmware Hub Device
            Name (_CID, EisaId ("PNP0C02"))  // Plug and Play ID for system board
            Name (_UID, 0x01)
            
            Method (_STA, 0, NotSerialized)
            {
                // Enable only in macOS
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)  // Device present, enabled, shown in UI
                }
                Else
                {
                    Return (0x00)  // Device not present in other OS
                }
            }
            
            // Memory resources for firmware hub
            Name (_CRS, ResourceTemplate ()
            {
                Memory32Fixed (ReadWrite,
                    0xFED10000,         // Base address
                    0x00001000,         // Length (4KB)
                    )
                    
                Memory32Fixed (ReadWrite,
                    0xFED18000,         // Base address
                    0x00001000,         // Length (4KB)
                    )
                    
                // Optional: I/O resources if needed
                // IO (Decode16,
                //     0x1000,             // Range Minimum
                //     0x1000,             // Range Maximum
                //     0x01,               // Alignment
                //     0x10,               // Length
                //     )
            })
            
            // Device Specific Method
            Method (_DSM, 4, Serialized)
            {
                Local0 = Package (0x02)
                {
                    // UUID for Intel Firmware Hub: 1F1B4BC5-8B86-48B5-816D-184C131D9D8E
                    ToUUID ("1F1B4BC5-8B86-48B5-816D-184C131D9D8E"),
                    
                    Package ()
                    {
                        // "fwhub-state" property
                        "fwhub-state", 
                        Buffer (0x01) { 0x01 }  // Enabled
                    }
                }
                Return (Local0)
            }
        }
    }
}