/*
 * SSDT-PPMC.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "PPMC", 0x00000000)
{
    External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)
    
    Scope (\_SB.PC00.LPCB)
    {
        Device (PPMC)
        {
            Name (_HID, "INT3A0D")
            Name (_CID, "PNP0C02")
            Name (_UID, One)
            
            Method (_STA, 0, NotSerialized)
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0B)  // Present and enabled
                }
                Return (Zero)
            }
            
            Name (_CRS, ResourceTemplate ()
            {
                Memory32Fixed (ReadWrite, 0xFED10000, 0x1000, )
                Memory32Fixed (ReadWrite, 0xFED18000, 0x1000, )
            })
            
            // Basic power management methods
            Method (_PTS, 1, NotSerialized)
            {
                // Prepare To Sleep - called before entering sleep state
                // Arg0: 1=S1, 2=S2, 3=S3, 4=S4, 5=S5
                Store (Arg0, PMSL)
            }
            
            Method (_WAK, 1, NotSerialized)
            {
                // Wake from Sleep
                Store (0x00, PMSL)
                Return (Package (0x02){0x00, 0x00})
            }
            
            Name (PMSL, 0x00)  // Sleep state register
        }
    }
}