/*
 * SSDT-ALS0.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "ALS0", 0)
{
    Scope (\)
    {
        Device (ALS0)
        {
            Name (_HID, "ACPI0008")
            Name (_CID, "PNP0C50")
            Method (_STA, 0, NotSerialized)
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Return (0)
            }
            Name (_ALI, 0x0140)
        }
    }
}