/*
 * SSDT-HID.dsl
 * Generated by SystemMaintenance
 * Date: 2026-01-01
 * Motherboard: Gigabyte Z790 GAMING X AX
 * Device Type: Motherboard
 * 
 *
 * NOTE: This is a template. Customize for your hardware.
 * Refer to Dortania guides for implementation details.
 */

DefinitionBlock ("", "SSDT", 2, "SYSM", "HIDD", 0x00000000)
{
 External (_SB_.PC00, DeviceObj)
    External (_SB_.PC00.LPCB, DeviceObj)

    
    Scope (\_SB.PC00.LPCB)
    {
        Device (HIDD)
        {
            Name (_HID, "PNP0C50")  // HID Device
            Name (_CID, "MSFT0001")
            Name (_UID, One)
            
            Method (_STA, 0, NotSerialized)
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0B)  // Present and enabled
                }
                Return (Zero)
            }
            
            Name (_CRS, ResourceTemplate ()
            {
                IO (Decode16, 0x0060, 0x0060, 0x01, 0x01)
                IO (Decode16, 0x0064, 0x0064, 0x01, 0x01)
                IRQ (Edge, ActiveHigh, Exclusive, ) {1}
            })
            
            // Simple _DSM method
            Method (_DSM, 4, Serialized)
            {
                Return (Package (0x02)
                {
                    ToUUID ("3D6D021E-F9B9-4B44-AD8F-B0ABE4FCFFD1"),
                    Package ()
                    {
                        "HIDWakeup",
                        Buffer (One) { 0x01 }
                    }
                })
            }
        }
    }
}